name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Compile
        shell: pwsh
        run: |
          mkdir out
          $files = Get-ChildItem -Recurse -Filter *.java | % { $_.FullName }
          javac -encoding UTF-8 -d out $files

      - name: Create Jar
        shell: pwsh
        run: |
          jar --create --file SortingVisualizer.jar --main-class SortingVisualizer -C out .

      - name: Build EXE
        shell: pwsh
        run: |
          jpackage `
            --type exe `
            --name SortingVisualizer `
            --input . `
            --main-jar SortingVisualizer.jar `
            --main-class SortingVisualizer `
            --icon logo.ico

      - uses: actions/upload-artifact@v4
        with:
          name: SortingVisualizer
          path: "*.exe"
