name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Compile
        shell: pwsh
        run: |
          if (Test-Path out) {
            Remove-Item out -Recurse -Force
          }

          New-Item -ItemType Directory -Path out | Out-Null

          $files = Get-ChildItem sortingvisualizer -Recurse -Filter *.java |
                   Select-Object -ExpandProperty FullName

          javac -encoding UTF-8 -d out $files

      - name: Create JAR
        shell: pwsh
        run: |
          jar --create `
            --file SortingVisualizer.jar `
            --main-class sortingvisualizer.SortingVisualizer `
            -C out .

      - name: Build EXE
        shell: pwsh
        run: |
          jpackage `
            --type exe `
            --name SortingVisualizer `
            --input . `
            --main-jar SortingVisualizer.jar `
            --main-class sortingvisualizer.SortingVisualizer `
            --icon logo.ico

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: SortingVisualizer-Windows
          path: |
            *.exe
            *.msi
