name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"

      - name: Compile
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path out
          Get-ChildItem -Recurse -Filter *.java | ForEach-Object {
              $_.FullName
          } | Out-File sources.txt

          javac -d out @sources.txt

      - name: Build Jar
        shell: pwsh
        run: |
          jar --create `
              --file SortingVisualizer.jar `
              --main-class SortingVisualizer `
              -C out .

      - name: Build EXE
        shell: pwsh
        run: |
          jpackage `
            --type exe `
            --name SortingVisualizer `
            --input . `
            --main-jar SortingVisualizer.jar `
            --main-class SortingVisualizer `
            --icon logo.ico

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: SortingVisualizer-Windows
          path: "*.exe"
